# This file was generated by GoReleaser. DO NOT EDIT.
cask "jotmd" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "e6f6f8d81627e031724e4ae0ee35734080edb77b300abb31014a9c86c550929c"
      url "https://github.com/gonfff/jotmd/releases/download/v#{version}/jotmd_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b05c5f52946b9dab781f6b96b5bc7e3330ecba3e3161f5f847aabd6f5134095b"
      url "https://github.com/gonfff/jotmd/releases/download/v#{version}/jotmd_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "jotmd"
  desc "Terminal Markdown notes app"
  homepage "https://github.com/gonfff/jotmd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jotmd"

  # No zap stanza required

end
