# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jotmd < Formula
  desc "Terminal Markdown notes app"
  homepage "https://github.com/gonfff/jotmd"
  version "0.0.2"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/gonfff/jotmd/releases/download/v0.0.2/jotmd_0.0.2_darwin_amd64.tar.gz"
    sha256 "c9d2ad3d5f17d1c7e02425080be1124d7bf47868989a7a3dc3bf96197c92ce81"

    define_method(:install) do
      bin.install "jotmd"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/gonfff/jotmd/releases/download/v0.0.2/jotmd_0.0.2_darwin_arm64.tar.gz"
    sha256 "fde1c38ce08a518c14cffc9ae9fed4bc35be6e0d8790fee0f6e4b90ac258c74d"

    define_method(:install) do
      bin.install "jotmd"
    end
  end
end
